import { appColors, appFonts, fontSizes, windowHeight, windowWidth } from "@src/themes";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    view: { flex: 1 },
    stepContainer: {
        flexDirection: "row",
        alignItems: "center",
        top: windowHeight(8)
    },
    iconColumn: {
        alignItems: "center",
        position: "relative",
    },
    line: {
        position: "absolute",
        width: 2,
        height: windowHeight(25),
        borderStyle: "dashed",
        borderLeftWidth: windowHeight(1),
        borderColor: appColors.gray,
        top: windowHeight(18),
    },
    labelColumn: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        flex: 1,
        paddingVertical: windowHeight(2.6),
        paddingHorizontal: windowHeight(4),
        marginHorizontal: windowHeight(0)
    },
    label: {
        fontWeight: "500",
        color: appColors.blackColor,
        paddingVertical: windowHeight(10),
        width: "85%",
        bottom: windowHeight(9),
        flex: 1,
        marginHorizontal: windowHeight(4)
    },
    mapLink: {
        color: appColors.primary,
        fontSize: fontSizes.FONT19,
        marginTop: windowHeight(3),
        textDecorationLine: "underline",
        marginHorizontal: windowWidth(15),
        fontFamily: appFonts.medium,
    },
    dashedLine: {
        height: 0.1,
        width: '100%',
        borderBottomWidth: windowHeight(0.9),
        borderColor: appColors.primaryGray,
        borderStyle: 'dashed',
        marginVertical: windowHeight(12),
    },
    line1: { borderBottomWidth: windowHeight(1), borderBottomColor: appColors.border, borderStyle: 'dashed', marginVertical: windowHeight(2) },
    MessageMainView: {
        width: windowWidth(100),
        justifyContent: "space-between",
    },
    MessageView: {
        alignItems: "center",
        justifyContent: "center", height: windowHeight(30),
        width: windowHeight(30),
        borderRadius: windowHeight(20),
        borderWidth: windowHeight(1),
        backgroundColor: appColors.whiteColor,
        elevation: 0.5,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 1,
    },
    safetyCallView: {
        alignItems: "center",
        justifyContent: "center", height: windowHeight(30),
        width: windowHeight(30),
        borderRadius: windowHeight(20),
        borderWidth: windowHeight(1),
        elevation: 0.5,
        backgroundColor: appColors.whiteColor,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 1,
    },
    starContainer: { alignItems: "flex-end", justifyContent: "center" },
    viewDetails: {
        color: appColors.whiteColor, textAlign: 'center', fontFamily: appFonts.medium,
        fontSize: fontSizes.FONT19,
    },
    textView: { height: windowHeight(37), width: '47.5%', borderRadius: windowHeight(5), backgroundColor: appColors.primary, justifyContent: 'center' },
    bottomView: { flexDirection: "row", marginHorizontal: windowHeight(2), marginTop: windowHeight(16), justifyContent: 'space-between' },
    paidText: {
        color: appColors.price, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        top: windowHeight(3),
    },
    statusText: {
        color: appColors.primaryText, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT19,
        top: windowHeight(3),
        flex: 1
    },
    bottomMainView: { marginHorizontal: windowHeight(2), flexDirection: 'row', justifyContent: "space-between", marginTop: windowHeight(7) },
    cashText: {
        color: appColors.primaryText, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        top: windowHeight(2),
    },
    paymentMethodText: {
        color: appColors.primaryText, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT19,
        top: windowHeight(2),
        flex: 1
    },
    viewBottom: { marginHorizontal: windowHeight(2), flexDirection: 'row', justifyContent: "space-between" },
    arrayView: { flexDirection: 'row', marginTop: windowHeight(2), gap: windowHeight(2.5), paddingVertical: windowHeight(2) },
    starPoint: {
        color: appColors.primaryText,
        fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        left: windowHeight(4)
    },
    starNumber: {
        color: appColors.gray,
        fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        marginHorizontal: windowHeight(3)
    },
    defaultImage: {
        height: windowHeight(35),
        width: windowHeight(35),
        resizeMode: 'contain',
        marginHorizontal: windowHeight(1),
    },
    scrollView: { marginHorizontal: windowWidth(20), marginVertical: windowHeight(17) },
    scrollMainView: { backgroundColor: appColors.whiteColor, padding: windowHeight(10), borderRadius: windowHeight(5), borderWidth: windowHeight(1), borderColor: appColors.border },
    container: { flexDirection: 'row', justifyContent: 'space-between' },
    authBg: { height: windowHeight(45), width: windowHeight(45), borderRadius: windowHeight(5) },
    platNumberView: { flexDirection: 'row', width: windowWidth(120), justifyContent: 'space-between', alignItems: 'center', marginTop: windowHeight(5) },
    corollaText: { color: appColors.primaryText, fontFamily: appFonts.semiBold },
    cLMV069: { color: appColors.primary, fontFamily: appFonts.semiBold },
    jonathan: {
        color: appColors.primaryText,
        fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT18,
    },
    dateTimeView: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: windowHeight(0) },
    rideIdView: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: windowHeight(8) },
    luggageView: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: windowHeight(7.8), marginBottom: windowHeight(2) },
    text: { color: appColors.primaryText, fontFamily: appFonts.medium },
    amountView: { flexDirection: 'row', justifyContent: 'space-between', marginTop: windowHeight(3) },
    bookView: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: windowHeight(3) },
    arrayView1: { flexDirection: "row", marginTop: windowHeight(2), alignItems: "center" },
    starPoint1: {
        color: appColors.primaryText,
        fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        marginLeft: windowHeight(2),
    },
    starNumber1: {
        color: appColors.gray,
        fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        marginLeft: windowHeight(3),
    },
    callingView: {
        flexDirection: "row", alignItems: "center", width: windowWidth(105),
        justifyContent: "space-between",
    },
    altisText: {
        color: appColors.primaryText, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT19,
        left: windowHeight(9),
        top: windowHeight(2),
        flex: 1
    },
    changeText: {
        color: appColors.primary, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT17,
        top: windowHeight(2),
        borderBottomWidth: windowHeight(1),
        borderBottomColor: appColors.primary,
    },
    travelPreferences: {
        color: appColors.gray, fontFamily: appFonts.regular,
        fontSize: fontSizes.FONT19,
        marginTop: windowHeight(0),
        flex: 1,
        marginHorizontal: windowHeight(3)
    },
    travelText: { color: appColors.gray, fontSize: fontSizes.FONT18, fontFamily: appFonts.regular, paddingHorizontal: windowHeight(5) },
    dot: { color: appColors.gray, fontSize: fontSizes.FONT25, bottom: windowHeight(5) },
    defultImage: {
        height: windowHeight(35),
        width: windowHeight(35),
        resizeMode: "contain",
        marginHorizontal: windowHeight(1),
    },
    userView: { flex: 1, marginHorizontal: windowHeight(6) },
    imageMainView: {
        backgroundColor: appColors.whiteColor,
        padding: windowHeight(10),
        borderRadius: windowHeight(5),
        borderWidth: windowHeight(1),
        borderColor: appColors.border,
        marginBottom: windowHeight(0),
        marginTop: windowHeight(14),
    },
    imageView: {
        flexDirection: "row",
        alignItems: "center",
    },
    border: {
        borderBottomWidth: windowHeight(8),
        borderBottomColor: appColors.border,
    },
    dotView:{ flexDirection: "row", alignItems: "center", paddingHorizontal: windowHeight(7) },
    dotMainView:{ flexDirection: "row", alignItems: "center", paddingHorizontal: windowHeight(7), marginTop: windowHeight(0) },
    viewDot:{ flexDirection: "row", alignItems: "center", paddingHorizontal: windowHeight(7), marginTop: windowHeight(5), top: windowHeight(2) },
    toyotaView:{ marginHorizontal: windowHeight(2), flexDirection: 'row', justifyContent: "space-between" },
    cityStatusesView:{ height: windowHeight(28), width: windowHeight(64), borderRadius: windowHeight(5), backgroundColor: appColors.primary, bottom: windowHeight(5), justifyContent: "center", paddingHorizontal: windowHeight(2) },
    cityStatusesViewLabel:{ color: appColors.whiteColor, textAlign: 'center', fontFamily: appFonts.medium, fontSize: fontSizes.FONT16 },
    citiesMainContainer:{ backgroundColor: appColors.whiteColor, padding: windowHeight(10), borderRadius: windowHeight(5), borderWidth: windowHeight(1), borderColor: appColors.border, marginBottom: windowHeight(0) },
    citiesContainer:{ paddingHorizontal: windowWidth(0), marginBottom: windowHeight(0) },
    citiesDate:{ color: appColors.primary, fontFamily: appFonts.medium, fontSize: fontSizes.FONT22 },
    stepType:{ marginBottom: windowHeight(17) },
})
export default styles;