import { ImageSourcePropType } from "react-native";

export type images = {
  authBg: ImageSourcePropType;
  line: ImageSourcePropType;
  offerBg: ImageSourcePropType;
  bellNotification: ImageSourcePropType;
  user: ImageSourcePropType;
  profileUser: ImageSourcePropType;
  promoCodeBg: ImageSourcePropType;
  rideDetail: ImageSourcePropType;
  destination: ImageSourcePropType;
  bgOnboarding: ImageSourcePropType;
  bookRide: ImageSourcePropType;
  bookRideDark: ImageSourcePropType;
  trip: ImageSourcePropType;
  tripDark: ImageSourcePropType;
  auto: ImageSourcePropType;
  bike: ImageSourcePropType;
  carTwo: ImageSourcePropType;
  freight: ImageSourcePropType;
  parcel: ImageSourcePropType;
  verticalLine: ImageSourcePropType;
  promoCodeList: ImageSourcePropType;
  offerBgDark: ImageSourcePropType;
  rideDetailDark: ImageSourcePropType;
  destinationDark: ImageSourcePropType;
  bgDarkOnboard: ImageSourcePropType;
  authBgDark: ImageSourcePropType;
  mapEngland: ImageSourcePropType;
  french: ImageSourcePropType;
  spanish: ImageSourcePropType;
  arabic: ImageSourcePropType;
  euro: ImageSourcePropType;
  dollar: ImageSourcePropType;
  rs: ImageSourcePropType;
  english: ImageSourcePropType;
  splash: ImageSourcePropType;
  splashDark: ImageSourcePropType;
  googlePay: ImageSourcePropType;
  creditCard: ImageSourcePropType;
  paypal: ImageSourcePropType;
  cash: ImageSourcePropType;
  lineBottom: ImageSourcePropType;
  line2: ImageSourcePropType;
  walletBg: ImageSourcePropType;
  carPrime: ImageSourcePropType;
  rideLogo: ImageSourcePropType;
  scheduled: ImageSourcePropType;
  pin: ImageSourcePropType;
  car: ImageSourcePropType;
  noInternet: ImageSourcePropType;
  maintenance: ImageSourcePropType;
  noLocation: ImageSourcePropType;
  noServices: ImageSourcePropType;
  noBalance: ImageSourcePropType;
  discount: ImageSourcePropType;
  or: ImageSourcePropType;
  otpVerify: ImageSourcePropType;
  noVehicle: ImageSourcePropType;
  noOffer: ImageSourcePropType;
  noService: ImageSourcePropType;
  defultImage: ImageSourcePropType;
  noRide: ImageSourcePropType;
  noTicket: ImageSourcePropType;
  activeRideGo: ImageSourcePropType;
  splashBg: ImageSourcePropType;
  loaderGIF: ImageSourcePropType;
  noTicketDark: ImageSourcePropType;
  noLocationDark: ImageSourcePropType;
  noBalanceDark: ImageSourcePropType;
  noVehicleDark: ImageSourcePropType;
  noOfferDark: ImageSourcePropType;
  noServiceDark: ImageSourcePropType;
  maintenanceDark: ImageSourcePropType;
  noRideDark: ImageSourcePropType;
  noInternetDark: ImageSourcePropType;
  darkLine: ImageSourcePropType;
  noSignin: ImageSourcePropType;
  noSigninDark: ImageSourcePropType;
  otpDark: ImageSourcePropType;
  splashUser: ImageSourcePropType;
  success: ImageSourcePropType;
  rentalBanner: ImageSourcePropType;
  packagebanner: ImageSourcePropType;
  noServiceImage: ImageSourcePropType;
  noServiceImageDark: ImageSourcePropType;
  imagePlaceholder: ImageSourcePropType;
  profileBackground: ImageSourcePropType;
  waiting: ImageSourcePropType;
  cardBackground: ImageSourcePropType;
  soon: ImageSourcePropType;
  noChat: ImageSourcePropType
};

const Images: images = {
  authBg: require("@assets/images/authImage/authBg.png"),
  otpDark: require("@assets/images/authImage/otpDark.png"),
  line: require("@assets/images/gif/line.gif"),
  success: require("@assets/images/gif/success.gif"),
  noService: require("@assets/images/gif/noService.gif"),
  bellNotification: require("@assets/images/notification/bellNotification.png"),
  offerBg: require("@assets/images/homeScreenImage/offerBg.png"),
  rideLogo: require("@assets/images/homeScreenImage/rideLogo.png"),
  user: require("@assets/images/homeScreenImage/user.png"),
  profileUser: require("@assets/images/profileImage/profileUser.png"),
  promoCodeBg: require("@assets/images/profileTab/promoCode.png"),
  rideDetail: require("@assets/images/rideScreen/rideDetail.png"),
  bgOnboarding: require("@assets/images/onBoarding/bgOnboarding.png"),
  promoCodeList: require("@assets/images/profileImage/promoCodeList.png"),
  offerBgDark: require("@assets/images/homeScreenImage/offerBgDark.png"),
  rideDetailDark: require("@assets/images/rideScreen/rideDetailDark.png"),
  bgDarkOnboard: require("@assets/images/onBoarding/bgDarkOnboard.png"),
  authBgDark: require("@assets/images/authImage/authBgDark.png"),
  splash: require("@assets/images/splash/splash.png"),
  splashDark: require("@assets/images/splash/splashDark.png"),
  cash: require("@assets/images/payment/cash.png"),
  lineBottom: require("@assets/images/line.png"),
  line2: require("@assets/images/line2.png"),
  walletBg: require("@assets/images/walletBg.png"),
  pin: require("@assets/images/map/pin.png"),
  car: require("@assets/images/map/car.png"),
  noInternet: require("@assets/images/noInternet/noInternet.png"),
  maintenance: require("@assets/images/noInternet/maintenance.png"),
  noLocation: require("@assets/images/noInternet/noLocation.png"),
  noServices: require("@assets/images/noInternet/noService.png"),
  noBalance: require("@assets/images/noInternet/noBalance.png"),
  discount: require("@assets/images/discount/discount.png"),
  or: require("@assets/images/or.png"),
  otpVerify: require("@assets/images/authImage/otp.png"),
  noVehicle: require("@assets/images/noInternet/noVehicle.png"),
  noOffer: require("@assets/images/noInternet/noOffer.png"),
  defultImage: require("@assets/images/profileImage/defultImage.png"),
  noRide: require("@assets/images/noInternet/noRide.png"),
  noTicket: require("@assets/images/noInternet/noTicket.png"),
  activeRideGo: require("@assets/images/gif/activeRideGo.gif"),
  loaderGIF: require("@assets/images/gif/loader.gif"),
  noTicketDark: require("@assets/images/noInternet/noTicketDark.png"),
  noLocationDark: require("@assets/images/noInternet/noLocationDark.png"),
  noBalanceDark: require("@assets/images/noInternet/noBalanceDark.png"),
  noVehicleDark: require("@assets/images/noInternet/noVehicleDark.png"),
  noOfferDark: require("@assets/images/noInternet/noOfferDark.png"),
  noServiceDark: require("@assets/images/noInternet/noServiceDark.png"),
  maintenanceDark: require("@assets/images/noInternet/maintenanceDark.png"),
  noRideDark: require("@assets/images/noInternet/noRideDark.png"),
  noInternetDark: require("@assets/images/noInternet/noInternetDark.png"),
  darkLine: require("@assets/images/gif/darkLine.gif"),
  noSignin: require("@assets/images/noInternet/noSignin.png"),
  noSigninDark: require("@assets/images/noInternet/noSigninDark.png"),
  paypal: require("@assets/images/payment/payPal.png"),
  creditCard: require("@assets/images/payment/creditCard.png"),
  googlePay: require("@assets/images/payment/googlePay.png"),
  splashUser: require("@assets/images/splash/splashUser.png"),
  waiting: require("@assets/images/gif/waiting.gif"),
  packagebanner: require("@assets/images/homeScreenImage/packageBanner.png"),
  rentalBanner: require("@assets/images/homeScreenImage/rentalBanner.png"),
  noServiceImage: require("@assets/images/noInternet/noServiceImage.png"),
  noServiceImageDark: require("@assets/images/noInternet/noServiceImageDark.png"),
  imagePlaceholder: require("@assets/images/noInternet/image.png"),
  timerRound: require("@assets/images/rideScreen/timerRound.png"),
  profileBackground: require("@assets/images/profileImage/profileBackground.png"),
  cardBackground: require("@assets/images/wallet/cardBackground.png"),
  soon: require("@assets/images/wallet/soon.png"),
  noChat: require("@assets/images/noInternet/noChat.png")

};
export default Images;
